---
title: "qc_plots"
author: "Pascale Goertler"
date: '2022-07-15'
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Integrate data

```{r data}
lis <- read.csv("data_clean/clean_lis.csv") # lisbon weir
rv <- read.csv("data_clean/clean_rv.csv") # rio vista
shw <- read.csv("data_clean/clean_shw.csv") # sherwood harbor
yb <- read.csv("data_clean/clean_yb.csv") # yolo bypass

# integrated data published on EDI ()
colnames(rv)[2] <- "date"

rv$region <- "river_downstream"
shw$region <- "river_upstream"
yb$region <- "floodplain_bypass"

integrated_data <- rbind(rv, shw, yb)

integrated_data <- integrated_data[,-1] # group is not needed

integrated_data$date <- as.Date(integrated_data$date)
```

## QC plots

```{r qc plots, echo=FALSE}

integrated_data <- within(integrated_data, year <- format(integrated_data$date, "%Y"))

for(i in unique(integrated_data$year)){

    temp_dat <- integrated_data[integrated_data$year == i,]

    #mypath <- file.path("qc/", file.name = paste("qc_plot_", i, ".png", sep = ""))
    #png(file = mypath, width = 960, height = 480)

    plot(temp_dat$date, temp_dat$mean,
         col = ifelse(temp_dat$region == "river_downstream",'#469990', ifelse(temp_dat$region == "river_upstream", '#f032e6', '#BABABA')), pch = 2, xlab = "Date", ylab = "", yaxt="n", ylim = c(0,30))
    
    legend("topright", c(paste("Year", i, sep = " "), "river_downstream", "river_upstream", "floodplain_bypass", "mean", "max", "min"), pch = c(15, 15, 15, 15, 2, 1, 5), col = c('#FFFFFF', '#469990', '#f032e6', '#BABABA', '#404040', '#404040', '#404040'), bty ="n")

    par(new = TRUE)

    plot(temp_dat$date, temp_dat$max,
         col = ifelse(temp_dat$region == "river_downstream",'#469990', ifelse(temp_dat$region == "river_upstream", '#f032e6', '#BABABA')), pch = 1, xlab = "Date", ylab = "", yaxt="n", ylim = c(0,30))
    
    par(new = TRUE)

    plot(temp_dat$date, temp_dat$min,
         col = ifelse(temp_dat$region == "river_downstream",'#469990', ifelse(temp_dat$region == "river_upstream", '#f032e6', '#BABABA')), pch = 5, xlab = "Date", ylab = "Temperature (°C)", ylim = c(0,30))

    #dev.off()

    par(new = FALSE)
}

# 2013 looks wrong (maybe 2007 too?)
```

## 2013

```{r 2007, echo=FALSE}
colnames(lis)[2] <- "date"
lis$region <- "lis"
integrated_data_v2 <- rbind(rv, shw, yb, lis)

integrated_data_v2$date <- as.Date(integrated_data_v2$date)
integrated_data_v2 <- within(integrated_data_v2, year <- format(integrated_data_v2$date, "%Y"))

dat_2013 <- subset(integrated_data_v2, year =="2013")
unique(dat_2013$method)

method <- c("Pien_2020", "ybfmp_logger", "imputeTS", "WQ_w_fish")
pch <- c(0, 2, 1, 6)

pch_dat <- data.frame(method, pch)

dat_2013 <- merge(dat_2013, pch_dat, by = "method")

plot(dat_2013$date, dat_2013$min,
         col = ifelse(dat_2013$region == "river_downstream",'#469990', 
                      ifelse(dat_2013$region == "river_upstream", '#f032e6', ifelse(dat_2013$region == "floodplain_bypass", '#BABABA', '#404040' ))), pch = dat_2013$pch, xlab = "Date", ylab = "Temperature (°C)", ylim = c(0,30))

# need to substitute Lisbon Weir  data for 2013 (YBFMP logger data looks incorrect)
```

## LIS

```{r check lis, echo=FALSE}
lis$date <- as.Date(lis$date)
lis <- within(lis, year <- format(lis$date, "%Y"))

lis_2013 <- subset(lis, year =="2013")

colSums(is.na(dat_2013)) # good to go

```

## 2007

```{r 2007, echo=FALSE}
dat_2007 <- subset(integrated_data, year =="2007")

dat_2007 <- merge(dat_2007, pch_dat, by = "method")

plot(dat_2007$date, dat_2007$min,
         col = ifelse(dat_2007$region == "river_downstream",'#469990', 
                      ifelse(dat_2007$region == "river_upstream", '#f032e6', ifelse(dat_2007$region == "floodplain_bypass", '#BABABA', '#404040' ))), pch = dat_2007$pch, xlab = "Date", ylab = "Temperature (°C)", ylim = c(0,30))

# problem is the logger data again, but upstream 
shw <- within(shw, year <- format(shw$date, "%Y"))
head(shw)

shw_2007 <- subset(shw, year =="2007")
plot(shw_2007$date, shw_2007$mean)

# 2007-10-31 to 2007-11-27

# this will be fixed pre integration, changes made in f_make_shw.R July 2022

```

